// PROGRAM
export const MAX_PROGRAM_NAME_LENGTH = 50;

// COURSE
export const COURSE_CODE_REGEX = /^[A-Za-z0-9]*$/;
export const MAX_COURSE_CODE_LENGTH = 255;
export const MAX_COURSE_NAME_LENGTH = 50;

// GRAPH
export const MAX_GRAPH_NAME_LENGTH = 50;

// DOMAIN
export const MAX_DOMAIN_NAME_LENGTH = 50;
export const COLORS = [
	'PROSPEROUS_RED',
	'ENERGIZING_ORANGE',
	'SUNNY_YELLOW',
	'ELECTRIC_GREEN',
	'CONFIDENT_TURQUOISE',
	'MYSTERIOUS_BLUE',
	'MAJESTIC_PURPLE',
	'POWERFUL_PINK',
	'NEUTRAL_GRAY',
	'SERIOUS_BROWN'
] as readonly string[];
