// PROGRAM
export const MAX_PROGRAM_NAME_LENGTH = 50;

// COURSE
export const COURSE_CODE_REGEX = /^[A-Za-z0-9]*$/;
export const MAX_COURSE_CODE_LENGTH = 255;
export const MAX_COURSE_NAME_LENGTH = 50;

// GRAPH
export const MAX_GRAPH_NAME_LENGTH = 50;

// DOMAIN
export const MAX_DOMAIN_NAME_LENGTH = 50;
export const COLORS = {
	PROSPEROUS_RED: '#E03C31',
	ENERGIZING_ORANGE: '#EC6842',
	SUNNY_YELLOW: '#FFB81C',
	ELECTRIC_GREEN: '#6CC24A',
	CONFIDENT_TURQUOISE: '#00B8C8',
	MYSTERIOUS_BLUE: '#0076C2',
	MAJESTIC_PURPLE: '#6F1D77',
	POWERFUL_PINK: '#EF60A3',
	NEUTRAL_GRAY: '#5C5C5C',
	SERIOUS_BROWN: '#8D6E63'
};
export const COLOR_KEYS = Object.keys(COLORS) as (keyof typeof COLORS)[];

// SUBJECT
export const MAX_SUBJECT_NAME_LENGTH = 50;
