name: graph

services:
  caddy:
    image: docker.io/caddy:2.8-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  web:
    image: ghcr.io/prime-tu-delft/graph
    depends_on:
      - db
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}

  db:
    image: docker.io/postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
