allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@sveltejs/kit@2.69.3'
  - cookie@0.7.0
  - yaml@2.8.3
  - '@hono/node-server@1.19.13'
overrides:
  '@hono/node-server@<1.19.13': ^1.19.13
  cookie@<0.7.0: ^0.7.0
  yaml@>=2.0.0 <2.8.3: ^2.8.3
