
export type DomainStyle = 'PROSPEROUS_RED' | 'ENERGIZING_ORANGE' | 'SUNNY_YELLOW' | 'ELECTRIC_GREEN' | 'CONFIDENT_TURQUOISE' | 'MYSTERIOUS_BLUE' | 'MAJESTIC_PURPLE' | 'POWERFUL_PINK' | 'NEUTRAL_GRAY' | 'SERIOUS_BROWN'
export function validDomainStyle(object: any): object is DomainStyle {
	return ['PROSPEROUS_RED', 'ENERGIZING_ORANGE', 'SUNNY_YELLOW', 'ELECTRIC_GREEN', 'CONFIDENT_TURQUOISE', 'MYSTERIOUS_BLUE', 'MAJESTIC_PURPLE', 'POWERFUL_PINK', 'NEUTRAL_GRAY', 'SERIOUS_BROWN'].includes(object)
}
